name: GSBlockShuffle
version: '${version}'
main: me.stahu.gsblockshuffle.GSBlockShuffle
api-version: '1.20'
commands:
  gsblockshuffle:
    description: Your description
    usage: /<command>
    permission: gsblockshuffle.admin
    aliases: [gsbs]
  gsblockshuffle_set_game_state:
    description: Your description
    usage: /<command> <game_state>
    permission: gsblockshuffle.admin
    aliases: [gsbs_set_game_state]