#block settings
difficulty: 0
difficultyCap: 10 # hard capped at 1000
increaseDifficulty: true
increaseEveryNRounds: 1 # -1 if custom
customIncrease: [ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10 ] # increase at nth round
includeLowerDifficulties: false
includeVariants: true
treatAllAsIndividualBlocks: false

#round settings
roundTime: 300 #seconds
roundBreakTime: 10 #seconds
roundsPerGame: 1 # -1 for infinite
blockAssignmentMode: onePerPlayer # onePerPlayer | onePerTeam | onePerRound

#win settings
allPlayersRequiredForTeamWin: true
eliminateAfterRound: false
firstToWin: true # the round ends when the first player/team finds their block if true
teamScoreIncrementPerPlayer: false # team score increments for each player who found their block if false, otherwise only 1 point is awarded to the team that found their block
#teamWinBy: score # score | time
#winScore: 5

#teleport settings
teleportMode: amountPerTeam # disabled | amountPerPlayer | amountPerTeam | unlimited
amountOfTeleportsPerRound: 1

#miscelanous
#displaySplashWinnerMessage: false
showTeamCompass: true
muteSounds: false
disablePvP: true